<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_UserStatusLoca</name>
   <tag></tag>
   <elementGuidId>15934192-0dc9-4690-add3-e1dd7692065c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='Status']//ancestor::div[contains(@class,'oxd-input-field-bottom-space')]//*[contains(@class,'oxd-select-text--active')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
